version: '3'

services:
  wordpress:
    image: felipeelia/wordpress
    links:
      - mysql
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../dev:/var/www/html
      - ./htaccess_dev:/var/www/html/.htaccess
      - ./dev.ini:/usr/local/etc/php/conf.d/dev.ini
    env_file:
      - .env

  mysql:
    image: mariadb
    volumes:
      - ../db_data:/var/lib/mysql
    ports:
     - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    env_file:
      - .env

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    env_file:
      - .env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=${PMA_ARBITRARY}
      - PMA_HOST=${PMA_HOST}
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
    env_file:
      - .env
